name: qrc-volatility
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - pyyaml
  - pip:
      - qbraid
