#!/usr/bin/env python3
"""Run and verify the canonical 63-feature financial QRC simulation.

Two verification scopes are intentionally distinct:

``historical-oracle``
    Reproduce the exact aggregate metric oracle and fold-8 selected readout
    recorded at canonical commit 40ec805c on its original fold lineage.

``current-pipeline``
    Run the same frozen Case151 model and chronological selection procedure on
    folds generated by the current financial-classical pipeline. Verify model
    identity, frozen search grids, test isolation, output completeness, and the
    immutable historical reference hashes. Data-dependent metric and selected
    hyperparameter differences are recorded rather than relabelled as exact
    historical-oracle reproduction.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from transition_forecasting.qrc.palindrome_real_task_relevance_assay import (
    PalindromeRealTaskConfig,
    run_palindrome_real_task_relevance_assay,
)
from transition_forecasting.qrc.representation_candidates import CandidateFeatureConfig
from transition_forecasting.qrc.temporal_rydberg_chain import TemporalRydbergChainConfig
from transition_forecasting.qrc.temporal_rydberg_ladder import (
    StaggeredLadderGeometryConfig,
)

DEFAULT_FOLD_DIR = Path(
    "data/processed/global_transition_dataset_1d/purged_walk_forward_folds"
)
DEFAULT_OUTPUT_ROOT = Path(
    "results/transition_forecasting/qrc/case151_simulation/run"
)
DEFAULT_EXPECTED = Path("config/case151/expected_metrics.json")
DEFAULT_REFERENCE_ROOT = Path("reference/case151/freeze_001")
RIDGE_ALPHA_GRID = (0.1, 1.0, 10.0, 100.0, 1000.0)
CORRECTION_LAMBDA_GRID = (0.0, 0.25, 0.5, 1.0)
HISTORICAL_FOLD8_ALPHA = 0.1
HISTORICAL_FOLD8_LAMBDA = 0.25
REFERENCE_SHA256 = {
    "case151_encoded_sequence.csv": (
        "48359a61b773edf7779ab11e626b75ffae163245dcca6f85f4e402423458e21a"
    ),
    "case151_expected_curve.csv": (
        "a12d2eb30f21c869f96caf4699b5d72bbe75310f53932ced2335c7a3185cf161"
    ),
    "case151_freeze.json": (
        "a62e229e5ca141b1ef3df5f3f514f0271c7a1a80e271874e7c30887487fae8ef"
    ),
    "case151_freeze.npz": (
        "33c602d97ad55bc3e7272caa81fe44f21bca4b151384884662027507f3342201"
    ),
    "case151_geometry.csv": (
        "39cd16fb1aebf5e9fdd5e02ca8957398d1c6bc99c7f7cb0f02cf4bf96375358c"
    ),
}


def canonical_objects() -> dict[str, Any]:
    return {
        "config": PalindromeRealTaskConfig(
            folds=(4, 5, 6, 7, 8),
            lead=5,
            max_per_class=24,
            sequence_length=40,
            representations=("level_only", "level_instability"),
            temporal_conditions=(
                "ordered",
                "shuffled_keep_endpoint",
                "recent_tail",
                "static_endpoint",
            ),
            recent_tail_steps=5,
            ridge_alphas=RIDGE_ALPHA_GRID,
            correction_lambdas=CORRECTION_LAMBDA_GRID,
            inner_holdout_fraction=0.25,
            prequential_blocks=5,
            selection_seed=20260725,
            level_channel_name="log_volatility_level",
            fallback_level_channel=0,
            schedule_name="crossover_Ahalf_B_Ahalf",
        ),
        "candidate_features": CandidateFeatureConfig(
            instability_window=5,
            shock_window=5,
            short_slope_window=5,
            long_slope_window=20,
            q_low=0.01,
            q_high=0.99,
        ),
        "reservoir": TemporalRydbergChainConfig(
            n_atoms=6,
            spacing_short_um=8.5,
            spacing_long_um=10.0,
            defect_edge=1,
            defect_offset_um=0.6,
            c6_rad_um6_per_us=5_420_000.0,
            delta_center_rad_us=6.0,
            delta_span_rad_us=4.0,
            omega_base_rad_us=6.0,
            omega_mod_fraction=0.6,
            step_duration_us=0.02,
            probe_fractions=(0.25, 0.5, 1.0),
            max_phase_per_substep=0.25,
            max_substeps_per_step=512,
            shots=None,
            shot_seed=20260725,
        ),
        "geometry": StaggeredLadderGeometryConfig(
            longitudinal_spacing_um=8.5,
            row_spacing_um=9.0,
            stagger_fraction=0.35,
            bottom_spacing_scale=1.05,
            defect_site=4,
            defect_dx_um=0.35,
            defect_dy_um=-0.40,
        ),
        "interaction_scale": 1.25,
        "drive_phase_rad": 0.0,
    }


def _selected_row(frame: pd.DataFrame, *, interactions: str, scope: str) -> pd.Series:
    model = "palindrome_ordered_on" if interactions == "on" else "palindrome_ordered_off"
    rows = frame.loc[
        frame["model"].eq(model)
        & frame["representation"].eq("level_instability")
        & frame["condition"].eq("ordered")
        & frame["interactions"].eq(interactions)
        & frame["scope"].eq(scope)
    ]
    if len(rows) != 1:
        raise RuntimeError(
            f"expected one row for model={model}, interactions={interactions}, "
            f"scope={scope}; found {len(rows)}"
        )
    return rows.iloc[0]


def _assert_close(name: str, observed: float, expected: float, tolerance: float) -> None:
    if abs(observed - expected) > tolerance:
        raise RuntimeError(
            f"metric mismatch for {name}: observed={observed:.16g}, "
            f"expected={expected:.16g}, tolerance={tolerance:.3g}"
        )


def _grid_contains(value: float, grid: tuple[float, ...], tolerance: float = 1e-12) -> bool:
    return any(abs(value - candidate) <= tolerance for candidate in grid)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_reference_freeze(reference_root: Path) -> dict[str, str]:
    observed_names = {path.name for path in reference_root.iterdir() if path.is_file()}
    if observed_names != set(REFERENCE_SHA256):
        raise RuntimeError(
            "Case151 reference file set mismatch: "
            f"observed={sorted(observed_names)}, expected={sorted(REFERENCE_SHA256)}"
        )
    observed_hashes: dict[str, str] = {}
    for name, expected_hash in REFERENCE_SHA256.items():
        path = reference_root / name
        observed_hash = _sha256(path)
        if observed_hash != expected_hash:
            raise RuntimeError(
                f"Case151 reference hash mismatch for {name}: "
                f"observed={observed_hash}, expected={expected_hash}"
            )
        observed_hashes[name] = observed_hash
    return observed_hashes


def _metric_rows(run_dir: Path) -> dict[str, pd.Series]:
    pooled = pd.read_csv(run_dir / "pooled_metrics.csv")
    return {
        "selected_path": _selected_row(pooled, interactions="on", scope="path"),
        "selected_transition": _selected_row(
            pooled, interactions="on", scope="transition"
        ),
        "interaction_off_path": _selected_row(
            pooled, interactions="off", scope="path"
        ),
    }


def _metric_payload(
    rows: dict[str, pd.Series], expected: dict[str, Any]
) -> tuple[dict[str, dict[str, float]], dict[str, dict[str, float]], bool]:
    observed: dict[str, dict[str, float]] = {}
    deltas: dict[str, dict[str, float]] = {}
    exact_match = True
    for group, row in rows.items():
        observed[group] = {}
        deltas[group] = {}
        for metric, expected_value in expected["expected"][group].items():
            value = float(row[metric])
            delta = value - float(expected_value)
            observed[group][metric] = value
            deltas[group][metric] = delta
            exact_match = exact_match and abs(delta) <= 5e-10
    return observed, deltas, exact_match


def _verify_identity(run_dir: Path, *, verification_mode: str) -> dict[str, Any]:
    selections = pd.read_csv(run_dir / "readout_selections.csv")
    fold8 = selections.loc[
        selections["fold"].eq(8)
        & selections["model"].eq("palindrome_ordered_on")
        & selections["representation"].eq("level_instability")
        & selections["condition"].eq("ordered")
        & selections["interactions"].eq("on")
    ]
    if len(fold8) != 1:
        raise RuntimeError(f"expected one fold-8 selected readout row, found {len(fold8)}")

    selected_alpha = float(fold8.iloc[0]["selected_alpha"])
    selected_lambda = float(fold8.iloc[0]["selected_lambda"])
    if not _grid_contains(selected_alpha, RIDGE_ALPHA_GRID):
        raise RuntimeError(
            f"fold8.selected_alpha={selected_alpha!r} is outside the frozen grid "
            f"{RIDGE_ALPHA_GRID!r}"
        )
    if not _grid_contains(selected_lambda, CORRECTION_LAMBDA_GRID):
        raise RuntimeError(
            f"fold8.selected_lambda={selected_lambda!r} is outside the frozen grid "
            f"{CORRECTION_LAMBDA_GRID!r}"
        )

    historical_selection_match = (
        abs(selected_alpha - HISTORICAL_FOLD8_ALPHA) <= 1e-12
        and abs(selected_lambda - HISTORICAL_FOLD8_LAMBDA) <= 1e-12
    )
    if verification_mode == "historical-oracle":
        _assert_close(
            "fold8.selected_alpha",
            selected_alpha,
            HISTORICAL_FOLD8_ALPHA,
            1e-12,
        )
        _assert_close(
            "fold8.selected_lambda",
            selected_lambda,
            HISTORICAL_FOLD8_LAMBDA,
            1e-12,
        )

    diagnostics = pd.read_csv(run_dir / "feature_diagnostics.csv")
    selected = diagnostics.loc[
        diagnostics["model"].eq("palindrome_ordered_on")
        & diagnostics["representation"].eq("level_instability")
        & diagnostics["condition"].eq("ordered")
        & diagnostics["interactions"].eq("on")
    ]
    if selected.empty or not selected["feature_width"].eq(63).all():
        raise RuntimeError("canonical selected QRC must use exactly 63 occupation/pair features")

    summary = json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))
    if summary.get("test_rows_used") != 0:
        raise RuntimeError("Case151 run used fixed-test rows")
    if summary.get("qrc_head_fit_intercept") is not False:
        raise RuntimeError("Case151 QRC head must remain intercept-free")
    if summary.get("folds") != [4, 5, 6, 7, 8]:
        raise RuntimeError(f"unexpected Case151 folds: {summary.get('folds')!r}")
    if summary.get("lead") != 5:
        raise RuntimeError(f"unexpected Case151 lead: {summary.get('lead')!r}")

    for name in (
        "pooled_metrics.csv",
        "readout_selections.csv",
        "feature_diagnostics.csv",
        "summary.json",
    ):
        if not (run_dir / name).is_file():
            raise RuntimeError(f"missing Case151 output: {run_dir / name}")

    return {
        "feature_bank": "occupation_pair_raw",
        "feature_width": 63,
        "fold8_selected_alpha": selected_alpha,
        "fold8_selected_lambda": selected_lambda,
        "ridge_alpha_grid": list(RIDGE_ALPHA_GRID),
        "correction_lambda_grid": list(CORRECTION_LAMBDA_GRID),
        "fold8_selection_grid_verified": True,
        "historical_fold8_selected_alpha": HISTORICAL_FOLD8_ALPHA,
        "historical_fold8_selected_lambda": HISTORICAL_FOLD8_LAMBDA,
        "historical_fold8_selection_match": historical_selection_match,
        "test_rows_used": 0,
        "qrc_head_fit_intercept": False,
        "folds": [4, 5, 6, 7, 8],
        "lead": 5,
    }


def verify_run(
    run_dir: Path,
    expected_path: Path,
    *,
    verification_mode: str = "historical-oracle",
    reference_root: Path = DEFAULT_REFERENCE_ROOT,
    tolerance: float = 5e-10,
) -> dict[str, Any]:
    if verification_mode not in {"historical-oracle", "current-pipeline"}:
        raise ValueError(f"unsupported verification mode: {verification_mode}")

    expected = json.loads(expected_path.read_text(encoding="utf-8"))
    rows = _metric_rows(run_dir)
    observed_metrics, metric_deltas, historical_metric_match = _metric_payload(
        rows, expected
    )
    if verification_mode == "historical-oracle":
        for group, row in rows.items():
            for metric, value in expected["expected"][group].items():
                _assert_close(
                    f"{group}.{metric}", float(row[metric]), float(value), tolerance
                )

    identity = _verify_identity(run_dir, verification_mode=verification_mode)
    reference_hashes = verify_reference_freeze(reference_root)
    report = {
        "schema_version": 3,
        "status": "verified",
        "run_id": run_dir.name,
        "verification_mode": verification_mode,
        "canonical_commit": expected["canonical_commit"],
        "source_run": expected["source_run"],
        **identity,
        "historical_metric_oracle_applied": verification_mode == "historical-oracle",
        "historical_metric_match": historical_metric_match,
        "historical_reference_hashes_verified": True,
        "historical_reference_hashes": reference_hashes,
        "historical_reference_metrics": {
            group: {metric: float(value) for metric, value in metrics.items()}
            for group, metrics in expected["expected"].items()
            if group in rows
        },
        "observed_metrics": observed_metrics,
        "metric_deltas_vs_historical_reference": metric_deltas,
        "metric_tolerance": tolerance,
        "interpretation": (
            "Exact historical metric and fold-8 selection reproduction on the "
            "canonical fold lineage."
            if verification_mode == "historical-oracle"
            else "Current-pipeline integration of the frozen Case151 model and "
            "chronological selection procedure. Historical metric and selected-"
            "hyperparameter differences are reported because the generated fold "
            "composition is not the canonical historical fold lineage."
        ),
    }
    (run_dir / "case151_reproduction_audit.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    return report


def archive_existing_failed_output(run_dir: Path, output_root: Path) -> Path | None:
    if not run_dir.exists():
        return None
    audit_path = run_dir / "case151_reproduction_audit.json"
    if audit_path.is_file():
        audit = json.loads(audit_path.read_text(encoding="utf-8"))
        if audit.get("status") == "verified":
            raise RuntimeError(f"refusing to replace verified Case151 output: {run_dir}")
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    archive_root = output_root / "failed_attempts"
    archive_root.mkdir(parents=True, exist_ok=True)
    destination = archive_root / f"{run_dir.name}-{timestamp}"
    suffix = 1
    while destination.exists():
        destination = archive_root / f"{run_dir.name}-{timestamp}-{suffix}"
        suffix += 1
    shutil.move(str(run_dir), str(destination))
    return destination


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fold-dir", type=Path, default=DEFAULT_FOLD_DIR)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--expected", type=Path, default=DEFAULT_EXPECTED)
    parser.add_argument("--reference-root", type=Path, default=DEFAULT_REFERENCE_ROOT)
    parser.add_argument(
        "--verification-mode",
        choices=("historical-oracle", "current-pipeline"),
        default="historical-oracle",
    )
    parser.add_argument("--verify-existing", action="store_true")
    parser.add_argument(
        "--archive-existing-failed",
        action="store_true",
        help="Preserve an unverified existing output under failed_attempts before rerun.",
    )
    args = parser.parse_args()
    run_dir = args.output_root / args.run_id
    if not args.verify_existing:
        if run_dir.exists():
            if not args.archive_existing_failed:
                raise RuntimeError(
                    f"Case151 output already exists: {run_dir}; use "
                    "--archive-existing-failed to preserve and retry"
                )
            archived = archive_existing_failed_output(run_dir, args.output_root)
            if archived is not None:
                print(f"Archived failed Case151 attempt: {archived}")
        objects = canonical_objects()
        run_dir = run_palindrome_real_task_relevance_assay(
            fold_dir=args.fold_dir,
            results_root=args.output_root,
            config=objects["config"],
            candidate_features=objects["candidate_features"],
            reservoir=objects["reservoir"],
            geometry=objects["geometry"],
            interaction_scale=float(objects["interaction_scale"]),
            drive_phase_rad=float(objects["drive_phase_rad"]),
            run_id=args.run_id,
        )
    report = verify_run(
        run_dir,
        args.expected,
        verification_mode=args.verification_mode,
        reference_root=args.reference_root,
    )
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
